Feature/generate open api spec
OpenManufacturingPlatform/sds-aspect-model-editor pull request #19
Opened 2022-11-04 16:16 UTC by michelu89

A new icon in the toolbar makes it possible to generate an open api from the valid aspect model.

2022-11-08 11:32 UTC, georgschmidtdumont requested changes

2022-11-08 11:32 UTC, georgschmidtdumont commented on core/apps/ame-e2e/src/fixtures/valid-documentation.html
> +<!doctype html>
Please add the copyright header.

2022-11-08 11:32 UTC, georgschmidtdumont commented on core/apps/ame-e2e/src/fixtures/valid-open-api.json
> +{
Please add the copyright header.

2022-11-08 11:32 UTC, georgschmidtdumont commented on core/apps/ame-e2e/src/fixtures/valid-open-api.yaml
> +---
Please add the copyright header.

2022-11-09 13:09 UTC, michelu89 commented on core/apps/ame-e2e/src/fixtures/valid-open-api.json
> +{
Cannot include copyright to json

2022-11-09 13:20 UTC, georgschmidtdumont approved these changes

2022-11-09 13:44 UTC, merged