Update doc to new version and change import export page
OpenManufacturingPlatform/sds-aspect-model-editor pull request #22
Opened 2022-12-01 09:15 UTC by michelu89

2022-12-01 09:32 UTC, atextor requested changes

2022-12-01 09:32 UTC, atextor commented on documentation/ame-guide/modules/ROOT/pages/namespaces-references.adoc
>  * `+/Users/<YOUR-USER-NAME>/aspect-model-editor+` (on Mac or Linux)
\* \`+/Users/\<YOUR-USER-NAME\>/aspect-model-editor+\` (on Mac)
\* \`/home/\<YOUR-USER-NAME\>/aspect-model-editor+\` (on Linux)

2022-12-01 09:36 UTC, michelu89 commented on documentation/ame-guide/modules/ROOT/nav.adoc
> +* xref:import-and-export-namespaces.adoc[Import and export namespace]
Currently only one namespace is imported or exported. But will be changed soon.

2022-12-02 10:55 UTC, atextor approved these changes

2022-12-02 15:15 UTC, merged